version: "3.9"

services:

  nats:
    extends:
      file: nats/docker-compose.nats.yaml
      service: nats
  nats-1:
    extends:
      file: nats/docker-compose.nats.yaml
      service: nats-1
  nats-2:
    extends:
      file: nats/docker-compose.nats.yaml
      service: nats-2

  jaeger:
    extends:
      file: log-trace/docker-compose.jegger.yaml
      service: jaeger

networks:
  nats_network:
    name: nats_network