version: '3.8'

services:
  server-chat-postgres:
    container_name: server-chat-postgres
    image: postgres:15.5
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "admin" ]
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: chat
    command: postgres -c wal_level=logical
  server-chat-redis:
    container_name: server-chat-redis
    image: redis:7.2.3-alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      timeout: 20s
      retries: 10
    ports:
      - "6379:6379"
