version: "3.9"
services:

  nats:
    container_name: nats
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks:
      - nats_network

  nats-1:
    container_name: nats-1
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - nats_network
    depends_on:
      - nats

  nats-2:
    container_name: nats-2
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - nats_network
    depends_on:
      - nats

networks:
  nats_network:
    name: nats_network