version: "3"

services:
  redis:
    image: redis:7.2.3-alpine
    container_name: redis
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      timeout: 20s
      retries: 10
    networks:
      default:
  server-user-edgedb:
    container_name: server-user-edgedb
    image: edgedb/edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
    ports:
      - "5656:5656"
  server-place-postgres-postgis:
    container_name: server-place-postgres-postgis
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: place
      POSTGRES_PASSWORD: place1234!
      POSTGRES_DB: place
    ports:
      - "5432:5432"
