version: "3.9"

services:

  redis:
    image: redis:7.2.3-alpine
    command: redis-server --port 6379
    labels:
      - "name=redis"
      - "mode=standalone"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      timeout: 20s
      retries: 10
    ports:
      - "6379:6379"
    networks:
      default: