steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'server:place:test:']

  - name: 'node'
    entrypoint: 'npm'
    args: ['run', 'server:place:test']