version: "3"

services:
  postgres-postgis-uuidv7:
    image: postgis/postgis:15-3.4
    ports:
      - "5432:5432"
    volumes:
      - ./../pgxn/pg_uuidv7/15/pg_uuidv7.so:/usr/lib/postgresql/15/lib/pg_uuidv7.so
      - ./../pgxn/pg_uuidv7/pg_uuidv7.control:/usr/share/postgresql/15/extension/pg_uuidv7.control
      - ./../pgxn/pg_uuidv7/pg_uuidv7--1.4.sql:/usr/share/postgresql/15/extension/pg_uuidv7--1.4.sql
      - ./init-extensions.sh:/docker-entrypoint-initdb.d/init-extensions.sh
    command: postgres -c wal_level=logical
    platform: linux/amd64 # arm64로 할 경우 각종 extension의 so파일 들이 동작 안할 수 있음.
